services:
  product-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product
    networks:
      - go-shop
    volumes:
      - database:/var/lib/postgresql/data

  category-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=category
    networks:
      - go-shop
    volumes:
      - category-database:/var/lib/postgresql/data

  product:
    build: ../../product
    ports:
      - "5000:5000"
    depends_on:
      - product-db
    networks:
      - go-shop

  category:
    build: ../../category-service
    ports:
      - "5001:5000"
    depends_on:
      - category-db
    networks:
      - go-shop

volumes:
  database: {}
  category-database: {}

networks:
  go-shop: {}
